### ISSUE TITLE
possible issues with multiprocessing

### ISSUE THREAD

**Issue by rfitak** [simonhmartin/genomics_general#12] opened 2018-12-10 11:37 UTC
Hi Simon,
I am running into some issues with the most recent version of popgenWindows.py.  I had used it before (maybe a year ago) without any problems.  I parsed and compressed my VCF input file without issue using parseVCF.py (see uncompressed format below).  When I run popgenWindows.py I get a series of error messages related to the multiprocessing module, and I think there is an issue reading across the various threads.  The program continues to run however, producing the progress report:

```9 windows queued, 6 results received, 0 results written```

numerous times in a never ending process.  Here is the error printed out:

```
1381 scaffolds will be excluded.started worker 0started worker 1Process Process-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "popgenWindows.py", line 44, in stats_wrapper
    statsDict.update(Aln.groupFreqStats())
  File "/Users/rfitak/Downloads/CAMEL/genomics_general/genomics.py", line 775, in groupFreqStats
    siteBaseCounts = np.apply_along_axis(binBaseFreqs,0,self.numArray[np.ix_(seqIdx,siteIdx)],asCounts=True)
TypeError: apply_along_axis() got an unexpected keyword argument 'asCounts'
Process Process-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "popgenWindows.py", line 44, in stats_wrapper
    statsDict.update(Aln.groupFreqStats())
  File "/Users/rfitak/Downloads/CAMEL/genomics_general/genomics.py", line 775, in groupFreqStats
    siteBaseCounts = np.apply_along_axis(binBaseFreqs,0,self.numArray[np.ix_(seqIdx,siteIdx)],asCounts=True)
TypeError: apply_along_axis() got an unexpected keyword argument 'asCounts'
```
My input file looks like this:
```
#CHROM	POS	DC158_53	DC269	DC399	DC400	DC402	DC408	DC423	DROM802	Drom439	Drom795	Drom796	Drom797	Drom800_55	Drom806	Drom816	Drom820	WC214	WC216	WC218	WC219	WC220	WC247	WC303_108	WC304	WC305
NW_006210177.1	864	G/G	G/G	G/G	G/G	G/G	G/G	G/G	G/A	G/G	A/A	G/A	G/A	G/G	G/G	A/A	A/A	G/G	G/G	G/G	G/G	G/G	G/G	G/G	G/G	G/G
NW_006210177.1	995	T/T	C/C	T/T	T/T	T/T	C/T	C/C	T/T	T/T	T/T	T/T	T/T	T/T	T/T	T/T	T/T	C/T	C/C	C/C	C/T	T/T	C/T	T/T	T/T	T/T
NW_006210177.1	1022	G/G	G/G	G/G	G/G	G/G	G/G	G/G	G/A	A/A	G/G	G/A	G/A	A/A	A/A	G/G	G/G	G/G	G/G	G/G	G/G	G/G	G/G	G/G	G/G	G/G
NW_006210177.1	1072	G/T	G/G	G/T	T/T	T/T	G/T	G/G	G/G	G/G	G/G	G/G	G/G	G/G	G/G	G/G	G/G	G/T	G/G	G/G	G/T	T/T	G/T	T/T	T/T	T/T
NW_006210177.1	1141	C/C	C/C	C/C	C/C	C/C	C/C	C/C	C/T	T/T	C/C	C/T	C/T	T/T	T/T	C/C	C/C	C/C	C/C	C/C	C/C	C/C	C/C	C/C	C/C	C/C
NW_006210177.1	1155	G/G	G/G	G/G	G/G	G/G	G/G	G/G	G/A	G/G	A/A	G/A	G/A	G/G	G/G	A/A	G/A	G/G	G/G	G/G	G/G	G/G	G/G	G/G	G/G	G/G
NW_006210177.1	1173	T/T	T/T	T/T	T/T	T/T	T/T	T/T	T/G	G/G	T/T	T/G	T/G	G/G	G/G	T/T	T/T	T/T	T/T	T/T	T/T	T/T	T/T	T/T	T/T	T/T
NW_006210177.1	1255	T/T	T/T	T/T	T/T	T/T	T/T	T/T	T/C	C/C	T/T	T/C	T/C	C/C	C/C	T/T	T/T	T/T	T/T	T/T	T/T	T/T	T/T	T/T	T/T	T/T
NW_006210177.1	1316	T/T	T/T	T/T	T/T	T/T	T/T	T/T	T/A	T/T	A/A	T/A	T/A	T/T	T/T	A/A	T/A	T/T	T/T	T/T	T/T	T/T	T/T	T/T	T/T	T/T
```

Furthermore, when I use individual based statistics, i.e. ```indHet``` or ```indPairDist``` the program runs without issue. I am using:
python 2.7.6
numpy==1.15.4

**Comment by simonhmartin** [comment] 2018-12-17 21:55
Sorry for the delay. Can you confirm that the error still occurs with the latest version of popgenWindows.py and genomics.py?

**Comment by rfitak** [comment] 2018-12-19 16:01
I checked the latest version and I still get the same issue.  However, I found that on both Mac OSX (v10.13.6) and Ubuntu (v14.04), I can get the popgenWindows.py script (with popFreq) to work perfectly as long as python is v2.7.15 and numpy v1.15.4.  I cannot get it to function with an earlier version of python.  This shouldn't be a problem for most people, as python virtualenvs are easy to setup, but worth a mention in the README regarding with versions of python/numpy you used for building the scripts.  

On another note, although using the above python/numpy I get popFreq/popDist/indPairDist/indHet to run perfectly, popPairDist fails and I haven't been able to track down the error in the code.  Again, your earlier versions of the python scripts ran fine (before the '--analysis' options were added).  

The command and input files are identical to that above, with the exception of '--analysis popPairDist'.  The command looks like this:
```bash
python2.7 \
   popgenWindows.py \
   --windType coordinate  \
   --windSize 100000 \
   --stepSize 50000 \
   --minSites 10 \
   --writeFailedWindows \
   --genoFile ../input.geno.gz \
   --outFile popFreq.100kb.csv.gz \
   --genoFormat phased \
   --exclude ../XY.exclude \
   --Threads 2 \
   --verbose \
   --population Drom DROM802,Drom439,Drom795,Drom796,Drom797,Drom800_55,Drom806,Drom816,Drom820 \
   --population DC DC158_53,DC269,DC399,DC400,DC402,DC408,DC423 \
   --population WC WC214,WC216,WC218,WC219,WC220,WC247,WC303_108,WC304,WC305 \
   --analysis popPairDist
```

and here is the error:
```
1381 scaffolds will be excluded.started worker 0started worker 1Sorter received result 1Sorter received result 2Sorter received result 3Sorter received result 4Sorter received result 5Sorter received result 6Process Process-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "popgenWindows.py", line 58, in stats_wrapper
    values = [round(statsDict[stat], roundTo) for stat in stats]
KeyError: 'dxy_Drom_DC'
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "popgenWindows.py", line 58, in stats_wrapper
    values = [round(statsDict[stat], roundTo) for stat in stats]
KeyError: 'dxy_Drom_DC'

9 windows queued, 6 results received, 0 results written.
...
```
Maybe there is an issue related to how the reference for each metric (e.g., dxy) in each population is coded and referenced (e.g., ```KeyError: 'dxy_Drom_DC'```)?

**Comment by simonhmartin** [comment] 2019-02-06 12:47
Sorry I had forgotten about this issue with dxy. It turns out it was just a bug that made the script ignore pairwise analyses (popPairDist) unless you had also requested within-population analysis (popDist)
It should be fixed now.

Thanks fopr the note about earlier versions of python/numpy. I will try figure out what the issue is.

**Closed** 2019-09-24 11:33 UTC
